# Generated by Django 4.2.1 on 2023-05-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_mobile_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp',
            field=models.CharField(blank=True, max_length=6, verbose_name='OTP'),
        ),
    ]
