# Generated by Django 4.1.7 on 2023-05-19 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_category_productsize_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='Product_Image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='Product_name',
        ),
        migrations.RenameField(
            model_name='productsize',
            old_name='product_size',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AddField(
            model_name='productsize',
            name='Quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productsize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.product'),
            preserve_default=False,
        ),
    ]
