# Generated by Django 4.2.1 on 2023-06-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsize',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
