# Generated by Django 4.2.1 on 2023-06-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_coupon_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='applicable_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('amount', 'Amount'), ('percentage', 'Percentage')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
