# Generated by Django 4.2.1 on 2023-07-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='min_amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
